#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Suomato\Luna;
$app = new Application('Luna 0.1.0');

$app->addCommands(Luna::commands());

$app->run();
