#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Suomato\Luna;

$app = new Application('Luna ' . Luna::$version);

$app->addCommands(Luna::commands());

$app->run();
